import test from 'node:test';
import assert from 'node:assert/strict';
import { collectVisibleImageFillRequirements, createResumableAssetExportPlan, evaluateStaticVisualAssetCoverage } from '../lib/static-visual-asset-gate.mjs';
const leaf = (value) => ({ value, provenance: { source: 'fixture', locator: '/x' } });
function imageNode(id, imageRef) { return leaf({ id: leaf(id), type: leaf('RECTANGLE'), style: leaf({ fills: [leaf({ type: leaf('IMAGE'), visible: leaf(true), imageRef: leaf(imageRef) })] }) }); }
function dualPlatformTruth({ pc = 2, mobile = 2 } = {}) { const nodes = (prefix, count) => Array.from({ length: count }, (_, i) => imageNode(`${prefix}-${i}`, `${prefix}-ref-${i}`)); return leaf({ platforms: leaf({ pc: leaf({ sections: leaf({ first: leaf({ nodes: leaf(nodes('pc', pc)) }) }) }), mobile: leaf({ sections: leaf({ first: leaf({ nodes: leaf(nodes('mobile', mobile)) }) }) }) }) }); }
function completeManifest(reqs) { const assets = {}; for (const r of reqs) assets[`${r.platform}:${r.nodeId}`] = { platform: r.platform, nodeId: r.nodeId, file: `assets/${r.nodeId}.png`, sha256: `${r.nodeId}-sha`, imageRefs: r.imageRefs }; return { assets, exportRun: { schema: 'yise-asset-export-plan/v1', partial: false, requiredSourceKeys: reqs.map((r) => `${r.platform}:${r.nodeId}`), completedSourceKeys: reqs.map((r) => `${r.platform}:${r.nodeId}`) }, failed: [], noUrl: [] }; }

test('recursive provenance unwrap preserves 342 PC and 467 mobile source scope', () => { const reqs = collectVisibleImageFillRequirements(dualPlatformTruth({ pc: 342, mobile: 467 })); assert.equal(reqs.filter((r) => r.platform === 'pc').length, 342); assert.equal(reqs.filter((r) => r.platform === 'mobile').length, 467); assert.equal(reqs.filter((r) => r.platform === 'default').length, 0); assert.equal(new Set(reqs.map((r) => `${r.platform}:${r.nodeId}`)).size, 809); });
test('visual asset audit blocks missing manifest, partial batch, and missing main IMAGE asset', () => { const truth = dualPlatformTruth({ pc: 1, mobile: 1 }); const reqs = collectVisibleImageFillRequirements(truth); const rendered = reqs.map((r) => ({ ...r, complete: true, visible: true })); const missing = evaluateStaticVisualAssetCoverage({ truth, renderedAssets: rendered, requiredPlatforms: ['pc', 'mobile'] }); assert.equal(missing.visualAssetsComplete, false); assert.ok(missing.failures.some((e) => e.reason === 'asset-manifest-missing')); const partialManifest = completeManifest(reqs); partialManifest.exportRun.partial = true; const partial = evaluateStaticVisualAssetCoverage({ truth, assetManifest: partialManifest, renderedAssets: rendered, requiredPlatforms: ['pc', 'mobile'] }); assert.equal(partial.complete, false); const missingHero = completeManifest(reqs); delete missingHero.assets['pc:pc-0']; const audit = evaluateStaticVisualAssetCoverage({ truth, assetManifest: missingHero, renderedAssets: rendered, requiredPlatforms: ['pc', 'mobile'] }); assert.ok(audit.failures.some((e) => e.reason === 'image-fill-asset-manifest-missing' && e.nodeId === 'pc-0')); });
test('dual-platform visual audit passes only with manifest provenance and rendered assets for every platform', () => { const truth = dualPlatformTruth({ pc: 2, mobile: 2 }); const reqs = collectVisibleImageFillRequirements(truth); const manifest = completeManifest(reqs); const rendered = reqs.map((r) => ({ platform: r.platform, nodeId: r.nodeId, complete: true, visible: true })); const audit = evaluateStaticVisualAssetCoverage({ truth, assetManifest: manifest, renderedAssets: rendered, requiredPlatforms: ['pc', 'mobile'] }); assert.equal(audit.complete, true); const missing = evaluateStaticVisualAssetCoverage({ truth, assetManifest: manifest, renderedAssets: rendered.filter((r) => r.platform !== 'mobile'), requiredPlatforms: ['pc', 'mobile'] }); assert.ok(missing.failures.some((e) => e.reason === 'image-fill-not-rendered' && e.platform === 'mobile')); });
test('visual audit blocks IMAGE fills without source imageRef provenance', () => { const truth = leaf({ platforms: leaf({ pc: leaf({ sections: leaf({ first: leaf({ nodes: leaf([imageNode('hero', '')]) }) }) }) }) }); const reqs = collectVisibleImageFillRequirements(truth); const audit = evaluateStaticVisualAssetCoverage({ truth, assetManifest: completeManifest(reqs), renderedAssets: [{ platform: 'pc', nodeId: 'hero', complete: true, visible: true }], requiredPlatforms: ['pc'] }); assert.equal(audit.complete, false); assert.ok(audit.failures.some((e) => e.reason === 'image-fill-image-ref-missing')); });
test('diagnostic fields classify zero-height rendered node', () => { const truth = dualPlatformTruth({ pc: 1, mobile: 0 }); const reqs = collectVisibleImageFillRequirements(truth); const audit = evaluateStaticVisualAssetCoverage({ truth, assetManifest: completeManifest(reqs), renderedAssets: [{ platform: 'pc', nodeId: 'pc-0', complete: true, visible: false, rect: { width: 100, height: 0 }, display: 'block', visibility: 'visible' }], requiredPlatforms: ['pc'] }); const failure = audit.failures.find((e) => e.nodeId === 'pc-0'); assert.equal(failure.diagnostic.category, 'zero-height-rendered-node'); assert.deepEqual(failure.diagnostic.rect, { width: 100, height: 0 }); });
test('baked owner requires owner and leaf DOM evidence', () => { const truth = dualPlatformTruth({ pc: 1, mobile: 0 }); const reqs = collectVisibleImageFillRequirements(truth); const manifest = completeManifest(reqs); manifest.assets['pc:pc-0'].bakedIntoOwner = { ownerNodeId: 'pc-owner', reason: 'explicit baked owner relation' }; manifest.assets['pc:pc-owner'] = { platform: 'pc', nodeId: 'pc-owner', file: 'assets/owner.png', sha256: 'owner-sha', imageRefs: ['pc-ref-0'] }; const leafRendered = [{ platform: 'pc', nodeId: 'pc-0', complete: true, visible: true }]; const missingOwner = evaluateStaticVisualAssetCoverage({ truth, assetManifest: manifest, renderedAssets: leafRendered, requiredPlatforms: ['pc'] }); assert.ok(missingOwner.failures.some((e) => e.reason === 'image-fill-owner-not-rendered')); const passed = evaluateStaticVisualAssetCoverage({ truth, assetManifest: manifest, renderedAssets: [...leafRendered, { platform: 'pc', nodeId: 'pc-owner', complete: true, visible: true }], requiredPlatforms: ['pc'] }); assert.equal(passed.complete, true); });
test('resumable export plan keeps same node IDs separate by platform', () => { const reqs = [{ platform: 'pc', nodeId: 'shared', imageRefs: ['pc-ref'] }, { platform: 'mobile', nodeId: 'shared', imageRefs: ['mobile-ref'] }]; const plan = createResumableAssetExportPlan({ requirements: reqs, batchSize: 40, previous: { completedSourceKeys: ['pc:shared'] } }); assert.deepEqual(plan.requiredSourceKeys, ['pc:shared', 'mobile:shared']); assert.deepEqual(plan.completedSourceKeys, ['pc:shared']); assert.deepEqual(plan.pendingBatches.map((b) => b.map((r) => `${r.platform}:${r.nodeId}`)), [['mobile:shared']]); });
test('resumable export plan preserves 95 source requirements and batches', () => { const reqs = Array.from({ length: 95 }, (_, i) => ({ platform: i % 2 ? 'mobile' : 'pc', nodeId: `n-${i}`, imageRefs: [`ref-${i}`] })); const plan = createResumableAssetExportPlan({ requirements: reqs, batchSize: 40 }); assert.equal(plan.schema, 'yise-asset-export-plan/v1'); assert.equal(plan.partial, true); assert.deepEqual(plan.pendingBatches.map((b) => b.length), [40, 40, 15]); });
